fragment Product on Product {
  id
  title
  description
  handle
  productType
  options {
    name
    values
  }
  variants(first: 250) {
    edges {
      node {
        id
        title
        availableForSale
        quantityAvailable
        compareAtPriceV2 {
          amount
          currencyCode
        }
        priceV2 {
          amount
          currencyCode
        }
        image {
          ...Image
        }
        selectedOptions {
          name
          value
        }
      }
    }
  }
  priceRange {
    minVariantPrice {
      amount
      currencyCode
    }
    maxVariantPrice {
      amount
      currencyCode
    }
  }
  productType
  onlineStoreUrl
  availableForSale
  images(first: 250) {
    edges {
      node {
        ...Image
      }
    }
  }
}

query GetProductByHandle($handle: String!) {
  product(handle: $handle) {
    ...Product
  }
}

query GetAllProducts($startAfter: String, $pageSize: Int = 250) {
  products(first: $pageSize, after: $startAfter) {
    edges {
      cursor
      node {
        ...Product
      }
    }
  }
}

query GetProductsOnCollection(
  $startAfter: String
  $pageSize: Int = 250
  $id: ID!
) {
  collection(id: $id) {
    products(first: $pageSize, after: $startAfter) {
      edges {
        cursor
        node {
          ...Product
        }
      }
    }
  }
}

query GetCollections {
  collections(first: 200) {
    edges {
      node {
        id
        handle
      }
    }
  }
}
