fragment _Product on Product {
  id
  title
  description
  handle
  productType
  options {
    name
    values
  }
  variants(first: 250) {
    edges {
      node {
        id
        title
        availableForSale
        quantityAvailable
        compareAtPriceV2 {
          amount
          currencyCode
        }
        priceV2 {
          amount
          currencyCode
        }
        image {
          ..._Image
        }
        selectedOptions {
          name
          value
        }
      }
    }
  }
  priceRange {
    minVariantPrice {
      amount
      currencyCode
    }
    maxVariantPrice {
      amount
      currencyCode
    }
  }
  productType
  onlineStoreUrl
  availableForSale
  images(first: 250) {
    edges {
      node {
        ..._Image
      }
    }
  }
}

query _GetProductByHandle($handle: String!) {
  product(handle: $handle) {
    ..._Product
  }
}

query _GetAllProducts($startAfter: String, $pageSize: Int = 250) {
  products(first: $pageSize, after: $startAfter) {
    edges {
      cursor
      node {
        ..._Product
      }
    }
  }
}

query _GetProductsOnCollection(
  $startAfter: String
  $pageSize: Int = 250
  $id: ID!
) {
  collection(id: $id) {
    products(first: $pageSize, after: $startAfter) {
      edges {
        cursor
        node {
          ..._Product
        }
      }
    }
  }
}

query _GetCollections {
  collections(first: 200) {
    edges {
      node {
        id
        handle
      }
    }
  }
}
