fragment _Cart on Cart {
  id
  checkoutUrl
  lines(first: 250) {
    edges {
      node {
        id
        quantity
        merchandise {
          ... on ProductVariant {
            id
            selectedOptions {
              name
              value
            }
            title
            availableForSale
            quantityAvailable
            priceV2 {
              amount
              currencyCode
            }
            image {
              ..._Image
            }
            product {
              id
              title
              handle
              description
            }
          }
        }
        estimatedCost {
          subtotalAmount {
            amount
            currencyCode
          }
          totalAmount {
            amount
            currencyCode
          }
        }
        discountAllocations {
          discountedAmount {
            amount
            currencyCode
          }
        }
      }
    }
  }
  estimatedCost {
    subtotalAmount {
      amount
      currencyCode
    }
    totalAmount {
      amount
      currencyCode
    }
  }
}
